version: "3.9"

services:
  # api:
  #   image: julbetan/api_deportes:latest
  #   networks:
  #     - deploy_omnia_default
  #   container_name: api_deportes
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ENVIRONMENT=production
  #   depends_on:
  #     - db
  #   restart: always

  frontend:
    image: julbetan/frontend_omnia:latest
    networks:
      - deploy_omnia_default
    container_name: frontend_omnia
    ports:
      - "8090:80"
    restart: always

  # db:
  #   image: postgres:alpine
  #   networks:
  #     - deploy_omnia_default
  #   container_name: deportes-db
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - /root/projects/king_tide/db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: always

networks:
  deploy_omnia_default:
    name: deploy_omnia_default
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
