version: "3.9"
services:
  api:
    build:
      context: ../api_deportes
      dockerfile: Dockerfile.dev
    container_name: api_deportes
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ../api_deportes:/app
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend_kingtide
      dockerfile: Dockerfile.dev
    container_name: frontend_kingtide
    ports:
      - "5173:5173"
    volumes:
      - ../frontend_kingtide:/app
      - /app/node_modules
  db:
    image: postgres:alpine
    container_name: deportes-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ../api_deportes/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
